= modelCatalogueApiRoot

Sets and retrieves the current root of model catalogue api. Declared in `mc.core.modelCatalogueApiRoot` module
inside <<_mc_core, "mc.core" Angular Package>>.

== Usage

You can inject the value in any construct in the run phase (service, factory, controller, etc.). The value is string pointing
to the root of the model catalogue core REST API.

[source,javascript]
----
angular
.module('foo', ['mc.core.modelCatalgoueApiRoot'])
.factory('bar', function($http, $log, modelCatalogueApiRoot) {
    $http.get(modelCatalogueApiRoot + '/bar').then(function(result){
        $log.info('Result: ' + result);
    });
});
----


== Customization

Default value is `/api/modelCatalogue/core` which
should be  sufficient if you create single page application. If you want to change the value (usually
because of context path changes) place code similar to following one in your layout page anywhere after where
angular resources are resolved.

[source,html]
----
<script type="text/javascript">
    angular
    .module('demo.config', ['mc.core.modelCatalogueApiRoot'])
    .value('modelCatalogueApiRoot', '${request.contextPath ?: ''}/api/modelCatalogue/core');
</script>
----

This is regular way http://docs.angularjs.org/guide/providers#value-recipe[how to set AngularJS values].

NOTE: Don't forget to depend on the module you used for customizing the value in your application module otherwise the changes
wouldn't be taken into account.
